### ISSUE TITLE
기존 블로그 글 업로드

### ISSUE THREAD

**Issue by overtae** [overtae/tae-log#5]
#### github blog

- [x] 컴퓨터 과학
  - [x] 데이터베이스
  - [x] 네트워크
  - [x] OS
- [x] iOS 프로그래밍
  - [x] 오토 레이아웃
  - [x] iOS 앱 개발
  - [x] Swift 문법 정리
- [ ] Python
  - [x] 알고리즘 
  - [ ] 백준
  - [x] 코드업
  - [x] 코딩도장
  - [x] 플라스크
  - [ ] 프로그래머스
  - [x] Python 문법 정리
- [x] 웹 프로그래밍
  - [x] HTML, CSS
  - [x] JavaScript
- [x] 기타
  - [x] Git, Github
  - [x] 기타 개발 관련

#### velog

- [x] 내일배움캠프 시리즈
- [x] TIL 시리즈
- [x] 코딩테스트 시리즈

**Comment by overtae** [comment]
> [!WARNING]
> `next-mdx-remote` 와 `remark-mermaidjs`, `rehype-mermiad` 플러그인을 사용했을 때 `Accessing import.meta directly is unsupported` 에러 발생

<details>
  <summary>에러 전체 내용 참고</summary>
  <div>

```
⚠ ./node_modules/mermaid-isomorphic/dist/mermaid-isomorphic.js
Critical dependency: Accessing import.meta directly is unsupported (only property access or destructuring is supported)

Import trace for requested module:
./node_modules/mermaid-isomorphic/dist/mermaid-isomorphic.js
./node_modules/remark-mermaidjs/dist/remark-mermaidjs.js
./src/components/post/detail/PostBody.tsx
./src/app/blog/(post)/[mainCategory]/[subCategory]/[slug]/page.tsx
 ⚠ ./node_modules/mermaid-isomorphic/dist/mermaid-isomorphic.js
Critical dependency: Accessing import.meta directly is unsupported (only property access or destructuring is supported)

Import trace for requested module:
./node_modules/mermaid-isomorphic/dist/mermaid-isomorphic.js
./node_modules/remark-mermaidjs/dist/remark-mermaidjs.js
./src/components/post/detail/PostBody.tsx
./src/app/blog/(post)/[mainCategory]/[subCategory]/[slug]/page.tsx
 ⨯ node_modules\mermaid-isomorphic\dist\mermaid-isomorphic.js (2:25) @ eval
 ⨯ TypeError: {}.resolve is not a function
    at eval (webpack-internal:///(rsc)/./node_modules/mermaid-isomorphic/dist/mermaid-isomorphic.js:7:19)
    at (rsc)/./node_modules/mermaid-isomorphic/dist/mermaid-isomorphic.js (D:\githubRepositories\tae-log\.next\server\vendor-chunks\mermaid-isomorphic.js:20:1)
    at __webpack_require__ (D:\githubRepositories\tae-log\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/remark-mermaidjs/dist/remark-mermaidjs.js:6:76)
    at (rsc)/./node_modules/remark-mermaidjs/dist/remark-mermaidjs.js (D:\githubRepositories\tae-log\.next\server\vendor-chunks\remark-mermaidjs.js:20:1)
    at __webpack_require__ (D:\githubRepositories\tae-log\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./src/components/post/detail/PostBody.tsx:13:74)
    at __webpack_require__.a (D:\githubRepositories\tae-log\.next\server\webpack-runtime.js:100:13)
    at eval (webpack-internal:///(rsc)/./src/components/post/detail/PostBody.tsx:1:21)
    at (rsc)/./src/components/post/detail/PostBody.tsx (D:\githubRepositories\tae-log\.next\server\app\blog\(post)\[mainCategory]\[subCategory]\[slug]\page.js:754:1) {
  type: 'TypeError',
  page: '/blog/ios-programming/swift/iosworkshop-03'
}
  1 | import { chromium } from 'playwright';
> 2 | const html = import.meta.resolve('../index.html');
    |                         ^
  3 | const mermaidScript = {
  4 |     url: import.meta.resolve('mermaid/dist/mermaid.js')
  5 | };
 ⚠ ./node_modules/mermaid-isomorphic/dist/mermaid-isomorphic.js
Critical dependency: Accessing import.meta directly is unsupported (only property access or destructuring is supported)

Import trace for requested module:
./node_modules/mermaid-isomorphic/dist/mermaid-isomorphic.js
./node_modules/remark-mermaidjs/dist/remark-mermaidjs.js
./src/components/post/detail/PostBody.tsx
./src/app/blog/(post)/[mainCategory]/[subCategory]/[slug]/page.tsx
 ⚠ ./node_modules/mermaid-isomorphic/dist/mermaid-isomorphic.js
Critical dependency: Accessing import.meta directly is unsupported (only property access or destructuring is supported)

Import trace for requested module:
./node_modules/mermaid-isomorphic/dist/mermaid-isomorphic.js
./node_modules/remark-mermaidjs/dist/remark-mermaidjs.js
./src/components/post/detail/PostBody.tsx
./src/app/blog/(post)/[mainCategory]/[subCategory]/[slug]/page.tsx
 GET /blog/ios-programming/swift/iosworkshop-03 500 in 28719ms
```

  </div>
</details>

- mermaid 문법을 처리하는 데 문제가 있음
- https://github.com/vercel/next.js/discussions/36369 참고해서 시도해보기
